# docker-compose run func-deploy
# docker-compose up -d func-debug
version: '3.8'
services:
  func-debug:
    build: 
      context: .
      target: func-debug
    container_name: func-debug
    volumes:
      - ./:/app    
    ports:
      - "7081:7081"
    tty: true
  spfx-debug:
    build: 
      context: .
      target: spfx-debug
    container_name: spfx-debug
    volumes:
      - ./:/app    
    ports:
      - "4321:4321"
      - "5432:5432"
    tty: true